"""offer_sender_recipient_viewed

Revision ID: 066144b06d24
Revises: 8d7f5609af20
Create Date: 2026-02-15 22:18:21.594587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '066144b06d24'
down_revision: Union[str, None] = '8d7f5609af20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('sender_id', sa.UUID(), nullable=False))
    op.add_column('offers', sa.Column('recipient_id', sa.UUID(), nullable=False))
    op.add_column('offers', sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('offers', sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'cancelled_at')
    op.drop_column('offers', 'viewed_at')
    op.drop_column('offers', 'recipient_id')
    op.drop_column('offers', 'sender_id')
    # ### end Alembic commands ###
