"""add_foreign_keys

Revision ID: 5b0f02d9054e
Revises: 1838690a9568
Create Date: 2026-02-15 21:33:58.440913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b0f02d9054e'
down_revision: Union[str, None] = '1838690a9568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'advertiser_profiles', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'creator_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'creator_profiles', type_='foreignkey')
    op.drop_constraint(None, 'advertiser_profiles', type_='foreignkey')
    # ### end Alembic commands ###
