"""deal_flow_v2_new_fields

Revision ID: 8d7f5609af20
Revises: 5b0f02d9054e
Create Date: 2026-02-15 22:06:13.622623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d7f5609af20'
down_revision: Union[str, None] = '5b0f02d9054e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deal_signatures', sa.Column('sms_code', sa.String(length=10), nullable=True))
    op.add_column('deal_signatures', sa.Column('sms_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('conditions', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('deals', sa.Column('video_count', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('platform_fee', sa.Integer(), nullable=False))
    op.add_column('deals', sa.Column('creator_payout', sa.Integer(), nullable=False))
    op.add_column('deals', sa.Column('work_submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('deals', sa.Column('dispute_reason', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('conditions', sa.String(), nullable=True))
    op.add_column('offers', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('offers', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('offers', sa.Column('video_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'video_count')
    op.drop_column('offers', 'end_date')
    op.drop_column('offers', 'start_date')
    op.drop_column('offers', 'conditions')
    op.drop_column('deals', 'dispute_reason')
    op.drop_column('deals', 'work_submitted_at')
    op.drop_column('deals', 'creator_payout')
    op.drop_column('deals', 'platform_fee')
    op.drop_column('deals', 'video_count')
    op.drop_column('deals', 'end_date')
    op.drop_column('deals', 'start_date')
    op.drop_column('deals', 'conditions')
    op.drop_column('deal_signatures', 'sms_sent_at')
    op.drop_column('deal_signatures', 'sms_code')
    # ### end Alembic commands ###
